<?php
return array(
	//'配置项'=>'配置值'
    'MODULE_ALLOW_LIST'=>array('Home','Admin'),
    //设置默认目录
    'DEFAULT_MODULE'=>'Home',
    //设置模板后缀
    'TMPL_TEMPLATE_SUFFIX'=>'.html',
    //设置默认主题目录
    'DEFAULT_THEME'=>'Default',
    //数据库配置
    'DB_TYPE'=>'pdo',
    'DB_USER'=>'root',
    'DB_PWD'=>'',
    'DB_PREFIX'=>'weibo_',
    'DB_DSN'=>'mysql:host=localhost;dbname=weibo;charset=UTF8',
    //URL模式
    'URL_MODEL'=>2,
    //缓存设置
    'DATA_CACHE_TYPE'=>'Memcache',
);